---
title: "Plotly Example"
output:
  html_document:
    df_print: paged
---

```{r}
library(reticulate)

use_python("/opt/anaconda3/bin/python")
```

```{r number, echo=FALSE}
step <- 3L
library(cubs)
cu <- cubs(36, 'lebedev')
```

## plotly figures should be implicitly rendered on print

```{python}

import numpy as np
import scipy as sp
from scipy.special import sph_harm

import plotly.graph_objects as go
import plotly.io as pio 
# pio.renderers.default = "browser"

#lm=input("l, m?").split()
#l=int(lm[0]); m=int(lm[1])
conestep = r.step

l = 15
m = 9

R = 10.
Np = 120
Nt = 60
Nr= 2
rhalf=Nr//2 -1

r = np.linspace(0.99*R, 1.01*R, Nr)
theta = np.linspace(0, np.pi, Nt)
phi = np.linspace(0, 2*np.pi, Np)

d_r = r[1]-r[0] 
d_theta = theta[1]-theta[0] 
d_phi = phi[1]-phi[0]

theta, phi, r = np.meshgrid(theta, phi, r)

#need l,m as inputs
Ylm = 1/r**(l+1) * sph_harm(m, l, phi, theta).real


# prefactors
oneoverr = 1/r
oneoverrsintheta = 1/(r*np.sin(theta)+1e-12)

costheta = np.cos(theta)[:,:,rhalf]
sintheta = np.sin(theta)[:,:,rhalf]
cosphi = np.cos(phi)[:,:,rhalf]
sinphi = np.sin(phi)[:,:,rhalf]

xx = R*sintheta*cosphi 
yy = R*sintheta*sinphi 
zz = R*costheta 


def radial_field(x,y,z):
    r2 = x**2 + y**2 + z**2
    maxr = np.sqrt(np.max(r2))
    return(-x/maxr, -y/maxr, -z/maxr)


u, v, w = radial_field(xx,yy,zz)

Rout = 1.2 
sizeref = 0.8
step = conestep


layout = go.Layout(
    plot_bgcolor="#FFF",  # Sets background color to white
    xaxis=dict(
        title="",
        linecolor="#BCCCDC",  # Sets color of X-axis line
        showgrid=False  # Removes X-axis grid lines
    ),
    yaxis=dict(
        title="",  
        linecolor="#BCCCDC",  # Sets color of Y-axis line
        showgrid=False,  # Removes Y-axis grid lines    
    )
)

fig = go.Figure(layout=layout)   

#fig = go.Figure()

fig.add_trace(go.Surface(x=xx, y=yy, z=zz, 
                surfacecolor=Ylm[:,:,rhalf], 
                showscale=False,  
                colorscale='PRGn')) #RdBu

fig.add_trace(go.Cone(
  x=Rout*np.concatenate(xx[::step, ::step]),
  y=Rout*np.concatenate(yy[::step, ::step]),
  z=Rout*np.concatenate(zz[::step, ::step]),
  u=np.concatenate(u[::step, ::step]),
  v=np.concatenate(v[::step, ::step]),
  w=np.concatenate(w[::step, ::step]),
  showlegend=False,
  showscale=False,
    anchor="tip",
  colorscale=[(0, "orange"), (0.5, "orange"), (1, "orange")],
  sizemode="absolute",
  sizeref=sizeref))

import plotly.graph_objects as go
import numpy as np
np.random.seed(42)

# Simulate data
returns = np.random.normal(0.01, 0.2, 100)
price = 100 * np.exp(returns.cumsum())
time = np.arange(100)

fig.update_layout(title_text="Y({0},{1})".format(l,m), plot_bgcolor="#FFF",showlegend=False,
    yaxis=dict(
        title="",  
        linecolor="#BCCCDC",  # Sets color of Y-axis line
        showgrid=False,  # Removes Y-axis grid lines    
    ))
fig.update_scenes(xaxis_visible=False, yaxis_visible=False,zaxis_visible=False )
fig.show()
```

